kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"labels":{"app":"ezlearning","app.openshift.io/runtime":"java","app.openshift.io/runtime-version":"openjdk-8-ubi8"},"name":"ezlearning","namespace":"project1"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"app":"ezlearning","deploymentconfig":"ezlearning"},"template":{"metadata":{"labels":{"app":"ezlearning","deploymentconfig":"ezlearning"}},"spec":{"containers":[{"env":[{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"key":"database-user","name":"secretmariadb"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"database-password","name":"secretmariadb"}}},{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"database-root-password","name":"secretmariadb"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"key":"database-name","name":"secretmariadb"}}},{"name":"APP_PROFILE","value":"‘prod’"},{"name":"DB_URL","value":"mariadb.attempt5.svc.cluster.local"}],"image":"image-registry.openshift-image-registry.svc:5000/attempt5/ez-learning-git-new:latest","name":"ezlearning","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"},{"containerPort":8778,"protocol":"TCP"}],"resources":{}}]}},"triggers":[{"imageChangeParams":{"automatic":true,"containerNames":["ezlearning"],"from":{"kind":"ImageStreamTag","name":"ezlearning:latest","namespace":"project1"}},"type":"ImageChange"},{"type":"ConfigChange"}]}}
  resourceVersion: '1531985'
  name: ezlearning
  uid: 57b42ea2-c456-4736-966c-290093b866a5
  creationTimestamp: '2022-07-13T15:48:32Z'
  generation: 218
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-07-13T15:48:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:revisionHistoryLimit': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"ezlearning"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"APP_PROFILE"}':
                      .: {}
                      'f:name': {}
                    'k:{"name":"DB_URL"}':
                      .: {}
                      'f:name': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8443,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8778,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-07-18T15:11:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"ezlearning"}':
                  'f:image': {}
          'f:triggers': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-08-13T15:45:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:replicas': {}
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"ezlearning"}':
                  'f:env':
                    'k:{"name":"APP_PROFILE"}':
                      'f:value': {}
                    'k:{"name":"DB_PASSWORD"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                    'k:{"name":"DB_URL"}':
                      'f:value': {}
                    'k:{"name":"DB_USERNAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:secretKeyRef': {}
                  'f:ports':
                    'k:{"containerPort":1738,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-08-26T10:27:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
  namespace: project1
  labels:
    app: ezlearning
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-ubi8
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ezlearning
        from:
          kind: ImageStreamTag
          namespace: project1
          name: 'ezlearning:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/project1/ezlearning@sha256:6e3fc4f1bc06dd836cdcf7f4b11778f11458b46ab71530827443bc9d856872b0
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: ezlearning
    deploymentconfig: ezlearning
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ezlearning
        deploymentconfig: ezlearning
    spec:
      containers:
        - name: ezlearning
          image: >-
            image-registry.openshift-image-registry.svc:5000/project1/ezlearning@sha256:6e3fc4f1bc06dd836cdcf7f4b11778f11458b46ab71530827443bc9d856872b0
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 1738
              protocol: TCP
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-password
            - name: APP_PROFILE
              value: prod
            - name: DB_URL
              value: 'jdbc:mysql://mysql.project1.svc.cluster.local:3306/sampledb'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 218
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: >-
              image-registry.openshift-image-registry.svc:5000/project1/ezlearning@sha256:6e3fc4f1bc06dd836cdcf7f4b11778f11458b46ab71530827443bc9d856872b0
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 53
  updatedReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-08-22T16:17:05Z'
      lastTransitionTime: '2022-08-22T16:17:05Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "ezlearning-53" successfully rolled out
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-08-26T10:27:58Z'
      lastTransitionTime: '2022-08-26T10:27:58Z'
      message: Deployment config has minimum availability.
  replicas: 1
  readyReplicas: 1
