kind: Service
apiVersion: v1
metadata:
  name: ezlearningservice
  namespace: project1
 
  
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 1738-tcp
      protocol: TCP
      port: 1738
      targetPort: 1738
  
  
  selector:
    app: ezlearning
    deploymentconfig: ezlearning
status:
  loadBalancer: {}
